corpus:
  subfields:
    - 2302 # Ecological Modeling
    - 2303 # Ecology
    - 2309 # Nature and Landscape Conservation
    - 1105 # Ecology, Evolution, Behavior and Systematics
    - 2611 # Modeling and Simulation
    - 2613 # Statistics and Probability
  min_year: 2010
  has_abstract: true
  per_page: 200
  db_path: D:/Projects/Lit_tool/data/openalex.duckdb
  cols_to_select: 
    - 'id'
    - 'doi'
    - 'title'
    - 'authorships'
    - 'cited_by_count'
    - 'publication_year'
    - 'publication_date'
    - 'primary_topic'
    - 'referenced_works'
    - 'abstract_inverted_index'
    - 'language'